-- MySQL Script generated by MySQL Workbench
-- Sun Jan 27 19:29:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `phone2` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `website` VARCHAR(255) NULL,
  `facebook` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(99) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `country_id`),
  INDEX `fk_region_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_region_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`county`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`county` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`, `region_id`),
  INDEX `fk_county_region1_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_county_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `mydb`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `ISO3` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `county_id` INT NOT NULL,
  PRIMARY KEY (`id`, `county_id`),
  INDEX `fk_agatur_cities_agatur_counties1_idx` (`county_id` ASC) VISIBLE,
  CONSTRAINT `fk_agatur_cities_agatur_counties1`
    FOREIGN KEY (`county_id`)
    REFERENCES `mydb`.`county` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `postal_code` VARCHAR(45) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `city_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `city_id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accomodation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accomodation_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facility` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agatur_accommodation_secondary_service_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agatur_accommodation_secondary_service_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accomodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accomodation` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `stars` INT NULL,
  `description_full` TEXT NULL,
  `description_short` TEXT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  `accomodation_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `address_id`, `contact_id`, `accomodation_type_id`),
  INDEX `fk_unitate_cazare_adresa1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_accomodation_contact1_idx` (`contact_id` ASC) VISIBLE,
  INDEX `fk_accomodation_accomodation_type1_idx` (`accomodation_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_unitate_cazare_adresa1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accomodation_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accomodation_accomodation_type1`
    FOREIGN KEY (`accomodation_type_id`)
    REFERENCES `mydb`.`accomodation_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accomodation_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accomodation_facility` (
  `facility_id` INT NOT NULL,
  `accomodation_id` INT NOT NULL,
  PRIMARY KEY (`facility_id`, `accomodation_id`),
  INDEX `fk_agatur_accommodations_has_agatur_accommodation_facilitie_idx` (`facility_id` ASC) VISIBLE,
  INDEX `fk_accomodation_facility_accomodation1_idx` (`accomodation_id` ASC) VISIBLE,
  CONSTRAINT `fk_agatur_accommodations_has_agatur_accommodation_facilities_2`
    FOREIGN KEY (`facility_id`)
    REFERENCES `mydb`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accomodation_facility_accomodation1`
    FOREIGN KEY (`accomodation_id`)
    REFERENCES `mydb`.`accomodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `id` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  `is_main` TINYINT NULL,
  `accomodation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_accomodation1_idx` (`accomodation_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_accomodation1`
    FOREIGN KEY (`accomodation_id`)
    REFERENCES `mydb`.`accomodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `accomodation_id` INT NOT NULL,
  `room_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `room_type_id`),
  INDEX `fk_room_accomodation1_idx` (`accomodation_id` ASC) VISIBLE,
  INDEX `fk_room_room_type1_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_accomodation1`
    FOREIGN KEY (`accomodation_id`)
    REFERENCES `mydb`.`accomodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `mydb`.`room_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agatur_package_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agatur_package_categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `parent_id` INT NOT NULL,
  PRIMARY KEY (`id`, `parent_id`),
  INDEX `fk_agatur_package_categories_agatur_package_categories1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_agatur_package_categories_agatur_package_categories1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`agatur_package_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`package_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`package_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`package` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `project_id` INT NOT NULL,
  `package_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`, `package_type_id`),
  INDEX `fk_package_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_package_package_type1_idx` (`package_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_package_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_package_package_type1`
    FOREIGN KEY (`package_type_id`)
    REFERENCES `mydb`.`package_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agatur_package_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agatur_package_category` (
  `package_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`package_id`, `category_id`),
  INDEX `fk_agatur_package_has_agatur_package_categories_agatur_pack_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_agatur_package_has_agatur_package_categories_agatur_pack_idx1` (`package_id` ASC) VISIBLE,
  CONSTRAINT `fk_agatur_package_has_agatur_package_categories_agatur_package1`
    FOREIGN KEY (`package_id`)
    REFERENCES `mydb`.`package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agatur_package_has_agatur_package_categories_agatur_packag1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`agatur_package_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offer` (
  `id` INT NOT NULL,
  `duration` INT NULL,
  `duration_unit` VARCHAR(45) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `package_id` INT NOT NULL,
  PRIMARY KEY (`id`, `package_id`),
  INDEX `fk_oferta_package1_idx` (`package_id` ASC) VISIBLE,
  CONSTRAINT `fk_oferta_package1`
    FOREIGN KEY (`package_id`)
    REFERENCES `mydb`.`package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuration` (
  `id` INT NOT NULL,
  `availability` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `room_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `offer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `room_id`, `currency_id`, `offer_id`),
  INDEX `fk_configuration_room1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_configuration_currency1_idx` (`currency_id` ASC) VISIBLE,
  INDEX `fk_configuration_offer1_idx` (`offer_id` ASC) VISIBLE,
  CONSTRAINT `fk_configuration_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_configuration_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_configuration_offer1`
    FOREIGN KEY (`offer_id`)
    REFERENCES `mydb`.`offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guest` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `count` INT NULL,
  `min_age` INT NULL,
  `max_age` INT NULL,
  `configuration_id` INT NOT NULL,
  PRIMARY KEY (`id`, `configuration_id`),
  INDEX `fk_guest_configuration1_idx` (`configuration_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_configuration1`
    FOREIGN KEY (`configuration_id`)
    REFERENCES `mydb`.`configuration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `address_id`),
  INDEX `fk_departament_adresa1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_departament_adresa1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `min_salary` INT NULL,
  `max_salary` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `data_nastere` DATETIME NULL,
  `contact_id` INT NULL,
  `hire_date` DATETIME NULL,
  `salary` INT NULL,
  `departament_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  PRIMARY KEY (`id`, `departament_id`, `job_id`),
  INDEX `fk_employee_departament1_idx` (`departament_id` ASC) VISIBLE,
  INDEX `fk_employee_job1_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_departament1`
    FOREIGN KEY (`departament_id`)
    REFERENCES `mydb`.`departament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`toi_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`toi_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`things_of_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`things_of_interest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  `toi_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `address_id`, `toi_type_id`),
  INDEX `fk_things_of_interest_adresa1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_things_of_interest_toi_type1_idx` (`toi_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_things_of_interest_adresa1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_things_of_interest_toi_type1`
    FOREIGN KEY (`toi_type_id`)
    REFERENCES `mydb`.`toi_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `job_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`, `job_id`, `employee_id`),
  INDEX `fk_job_history_job1_idx` (`job_id` ASC) VISIBLE,
  INDEX `fk_job_history_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_job_history_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_history_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address_id` INT UNSIGNED NOT NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `address_id`, `contact_id`),
  INDEX `fk_client_adresa1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_client_contact1_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_adresa1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recommended` TINYINT NULL,
  `created_date` DATETIME NULL,
  `message` TEXT NULL,
  `client_id` INT NOT NULL,
  `things_of_interest_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_comment_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_client_comment_things_of_interest1_idx` (`things_of_interest_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_comment_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_comment_things_of_interest1`
    FOREIGN KEY (`things_of_interest_id`)
    REFERENCES `mydb`.`things_of_interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rezervation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rezervation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_date` TIMESTAMP NULL,
  `client_id` INT NOT NULL,
  `configuration_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `configuration_id`),
  INDEX `fk_rezervation_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_rezervation_configurare1_idx` (`configuration_id` ASC) VISIBLE,
  CONSTRAINT `fk_rezervation_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rezervation_configurare1`
    FOREIGN KEY (`configuration_id`)
    REFERENCES `mydb`.`configuration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
