--Laborator 4 - prezentare curs
--1.1
GRANT CREATE SESSION TO ELEARN_APP_ADMIN;
--1.2
GRANT CREATE TABLE TO ELEARN_APP_ADMIN;
--1.3
GRANT CREATE ANY TABLE TO ELEARN_APP_ADMIN;
GRANT CREATE ANY INDEX TO ELEARN_APP_ADMIN;

select owner, object_name from all_objects where owner like '%ELEARN%';

--2.1
GRANT ALTER ON ELEARN_profesor1.FEEDBACK TO ELEARN_APP_ADMIN;

--2.2
--GRANT CREATE ANY TABLE TO ELEARN_APP_ADMIN;
--GRANT CREATE ANY INDEX TO ELEARN_APP_ADMIN;
GRANT CREATE VIEW TO ELEARN_APP_ADMIN ;

GRANT SELECT ON ELEARN_profesor1.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION; 
GRANT SELECT ON ELEARN_profesor2.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION; 
GRANT SELECT ON ELEARN_asistent3.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION;

GRANT CREATE TRIGGER TO ELEARN_APP_ADMIN;

GRANT INSERT ON ELEARN_profesor1.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION;
GRANT INSERT ON ELEARN_profesor2.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION;
GRANT INSERT ON ELEARN_asistent3.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION;

--2.3
GRANT CREATE PROCEDURE TO ELEARN_APP_ADMIN;
GRANT DELETE ON ELEARN_profesor1.FEEDBACK TO ELEARN_APP_ADMIN WITH GRANT OPTION;

